"""
Bridge package re-exporting backend.ml.reasoning for top-level modularity.
"""

from backend.ml.reasoning import (
    AnswerExtractor,
    BackwardChainingEngine,
    BackwardChainingResult,
    Clause,
    ConceptNode,
    ConceptualGraph,
    ConceptualRelationNode,
    ExtractedAnswer,
    Fact,
    ForwardChainingEngine,
    ForwardChainingResult,
    FraudExpertSystem,
    KnowledgeBase,
    Literal,
    ProofNode,
    ResolutionRefutationEngine,
    ResolutionRefutationResult,
    ResolutionStep,
    Rule,
    SemanticEdge,
    SemanticNetwork,
    SemanticNode,
    extract_facts_from_transaction,
)

__all__ = [
    "FraudExpertSystem",
    "KnowledgeBase",
    "Fact",
    "Rule",
    "extract_facts_from_transaction",
    "ForwardChainingEngine",
    "ForwardChainingResult",
    "BackwardChainingEngine",
    "BackwardChainingResult",
    "ProofNode",
    "AnswerExtractor",
    "ExtractedAnswer",
    "SemanticNetwork",
    "SemanticNode",
    "SemanticEdge",
    "ConceptualGraph",
    "ConceptNode",
    "ConceptualRelationNode",
    "ResolutionRefutationEngine",
    "ResolutionRefutationResult",
    "Clause",
    "Literal",
    "ResolutionStep",
]
